sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d

install:
  - docker-compose exec web sh -c "pip install coveralls"
  - docker-compose exec web sh -c "pip install pep8"

script:
  - docker-compose exec web sh -c "PYTHONWARNINGS=once coverage run --omit=*.virtualenvs*,*virtualenv* src/manage.py test --settings=sous_chef.settings_test member meal order notification delivery note billing page"
  - docker-compose exec web sh -c "python3 src/manage.py test --settings=sous_chef.settings_test_fr member meal order notification delivery note billing page"
  - docker-compose exec web sh -c "pep8 --count --show-source --exclude=migrations src/"

after_success:
  - docker-compose exec web sh -c "coveralls"
