version: '3'

services:

  db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feast
    volumes:
      - souschef_data:/var/lib/mysql
    networks:
      - backend

  web:
    environment:
      - SOUSCHEF_ENVIRONMENT_NAME=DEV
      - SOUSCHEF_VERSION=v1.0-beta
    restart: always
    build: .
    volumes:
      - souschef_static:/code/src/static
    depends_on:
      - db
    networks:
      - backend

  nginx:
    restart: always
    build: tools/nginx
    command: /bin/bash -c "nginx"
    ports:
      - "80:80"
    volumes:
      - souschef_static:/code/src/static
    depends_on:
      - web
    networks:
      - frontend
      - backend

volumes:
  souschef_data:
  souschef_static:

networks:
  frontend:
  backend:
